// <auto-generated />
namespace BTL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Xuat_Khau_Ruou : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Xuat_Khau_Ruou));
        
        string IMigrationMetadata.Id
        {
            get { return "202104200021242_Xuat_Khau_Ruou"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
